name: armis-alert
pipeline:
  - name: json_event
    external:
      name: json.parse-json

  - name: set_ecs_fields
    translator:
      - from: '{{json_event.message.alertId}}'
        to: event.id
      - from: '{{json_event.message.time}}'
        to: "@timestamp"
      - from: '{{json_event.message.time}}'
        to: event.start
      - from: '{{json_event.message.statusChangeTime}}'
        to: event.end
      - from: '{{json_event.message.type}}'
        to: event.action
      - from: '{{json_event.message.classification}}'
        to: event.category
      - from: '{{json_event.message.status}}'
        to: event.outcome
      - from: '{{json_event.message.affectedDevicesCount}}'
        to: event.count
      - from: '{{json_event.message.title}}'
        to: rule.name
      - from: '{{json_event.message.description}}'
        to: message
      - from: '{{json_event.message.deviceIds}}'
        to: host.id
      - from: '{{json_event.message.activityUUIDs}}'
        to: armis.alert.activity_uuids

  - name: set_static_fields
    set:
      - target: event.kind
        value: alert
      - target: observer.vendor
        value: Armis
      - target: observer.product
        value: Centrix

  - name: set_severity
    cases:
      - filter: '{{json_event.message.severity == "Critical"}}'
        set:
          - target: event.severity
            value: 4
      - filter: '{{json_event.message.severity == "High"}}'
        set:
          - target: event.severity
            value: 3
      - filter: '{{json_event.message.severity == "Medium"}}'
        set:
          - target: event.severity
            value: 2
      - filter: '{{json_event.message.severity == "Low"}}'
        set:
          - target: event.severity
            value: 1
